### ISSUE TITLE
Improve image uploader UI

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#129] opened 2013-03-05 23:13 UTC
Erik gave this feedback:

```
I'd suggest adjusting some indication states on the add files/upload/cancel to make it clear which button to click now. For instance, I don't think "Upload Now" does anything unless you've clicked "Add Files" but it took my a while to figure it out.
```

I agree that this could be a bit more intuitive. The simplest solution might be just completely hiding visibility of buttons until they are useful. For instance, only the "Add files" button should appear if there are no images uploaded yet.

**Comment by gsaines** [comment] 2013-03-06 13:54
Duplicate of #100

**Closed as completed by gsaines** 2013-03-06 13:54 UTC
Labels: Proposal
